### ISSUE TITLE
Reading DOS/PE headers - suggestion for code clarity

### ISSUE THREAD

**Issue by revosw** [eersoy93/vin32#1]
I see you are reversing the bytes where you read out the PE32 headers
https://github.com/eersoy93/vin32/blob/06474c74ab12ae726158dabc632aa2e1c4d21d00/parse.v#L178-L195
This library uses `.little_endian_u16()`, could it help increase the clarity of the code?
https://github.com/sha0coder-V/pe32/blob/24b1812f5f1d90a84982d1d940ae2c70dfe143db/pe32.v#L236-L268

**Comment by eersoy93** [comment]
Thank you for your indication.
